default: &default
  adapter: postgresql
  encoding: UTF8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: banking_api_development

test:
  <<: *default
  database: banking_api_test

production:
  <<: *default
  database: banking_api_production
  host: database # From docker-compose service's name
  username: stan
  password: <%= ENV['PG_PASSWORD'] %>
